### ISSUE TITLE
Automatic assignment of code under reviewing app  to developer app

### ISSUE THREAD

**Issue by kamontia** [kamontia/kimetaro#22]
CI step:
 In PR(Reviewing), run as developer app in Heroku
 After merged into master, application runs as production.

We can use `kimetaro-dev[1,2,3]` in review time.
Please assign reviewing code to role of `kimetaro-dev[1,2,3]` automatically on CircleCI and Heroku.

**Comment by chaspy** [comment]
## Added access token to CircleCI
![Screenshot 2019-05-02 13 35 57](https://user-images.githubusercontent.com/10370988/57056720-3d17fd80-6cdf-11e9-9a76-554b8b9f20b2.png)
