### ISSUE TITLE
Review Apps

### ISSUE THREAD

**Issue by chaspy** [kamontia/kimetaro#7]
Let's use `Heroku Review Apps` to improve review process.
https://devcenter.heroku.com/articles/github-integration-review-apps

**Comment by chaspy** [comment]
![Screenshot 2019-04-29 13 15 03](https://user-images.githubusercontent.com/10370988/56876213-d1385980-6a80-11e9-89ec-612ccc0c8c3c.png)

After deployed review app, change the value of `ACCESS TOKEN` to value of `ACCESS TOKEN DEV1`.
However...

![Screenshot 2019-04-29 13 16 06](https://user-images.githubusercontent.com/10370988/56876233-f7f69000-6a80-11e9-9994-911ca38b86b4.png)

😇

**Comment by kamontia** [comment]
@chaspy I'm sorry to be late. I think that this issue is not responsible for you. Both of review app and production app respond because call command is same.

**Comment by chaspy** [comment]
## TODO
- [x] Change calling command https://github.com/kamontia/kimetaro/pull/18
- [x] CI https://github.com/kamontia/kimetaro/issues/22

**Comment by chaspy** [comment]
done
